weights: yolov5s.pt
cfg: ''
data: /home/forest/BrandLogoChanger/data/starbucksMod/data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 500
batch_size: 128
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: 0,1,2,3,4,5,6,7
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 32
project: /home/forest/BrandLogoChanger/starbucksModResult
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /home/forest/BrandLogoChanger/starbucksModResult/exp2
